### ISSUE TITLE
Installation fails on macOS ("No matching distribution found for scipy==1.5.2")

### ISSUE THREAD

**Issue by TedTed** [opendp/smartnoise-samples#106]
Hi folks,

Following your installation instructions fails on macOS, at the `pip install -r requirements.txt` stage.

```
`--> pip install -r requirements.txt
Collecting jupyter==1.0.0
  Using cached jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
Collecting jupyter-client==6.1.7
  Using cached jupyter_client-6.1.7-py3-none-any.whl (108 kB)
Collecting jupyter-console==6.2.0
  Using cached jupyter_console-6.2.0-py3-none-any.whl (22 kB)
Collecting jupyter-core==4.6.3
  Using cached jupyter_core-4.6.3-py2.py3-none-any.whl (83 kB)
Collecting jupyterlab==2.2.9
  Using cached jupyterlab-2.2.9-py3-none-any.whl (7.9 MB)
Collecting jupyterlab-pygments==0.1.2
  Using cached jupyterlab_pygments-0.1.2-py2.py3-none-any.whl (4.6 kB)
Collecting jupyterlab-server==1.2.0
  Using cached jupyterlab_server-1.2.0-py3-none-any.whl (29 kB)
Collecting matplotlib==3.3.1
  Using cached matplotlib-3.3.1.tar.gz (38.8 MB)
Collecting numpy==1.19.1
  Using cached numpy-1.19.1.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting opendp-smartnoise==0.1.4
  Using cached opendp_smartnoise-0.1.4-py3-none-any.whl (167 kB)
Collecting pandas==1.1.0
  Using cached pandas-1.1.0.tar.gz (5.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting scipy==1.5.2
  Using cached scipy-1.5.2.tar.gz (25.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/damien/Documents/smartnoise-samples/venv/bin/python3.9 /Users/damien/Documents/smartnoise-samples/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/zf/b889zp6j40n1c5q7j4x71r4w0000gn/T/tmpav4k1mne
         cwd: /private/var/folders/zf/b889zp6j40n1c5q7j4x71r4w0000gn/T/pip-install-rox73tsf/scipy_c0c2de8487d94844a446bd6bc1cd1342
    Complete output (139 lines):
    setup.py:460: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /private/var/folders/zf/b889zp6j40n1c5q7j4x71r4w0000gn/T/pip-modern-metadata-5fbn848_'), proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
    Running from SciPy source directory.
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/Users/damien/Documents/smartnoise-samples/venv/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    openblas_lapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas not found in ['/Users/damien/Documents/smartnoise-samples/venv/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    openblas_clapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas,lapack not found in ['/Users/damien/Documents/smartnoise-samples/venv/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    flame_info:
    customize UnixCCompiler
      libraries flame not found in ['/Users/damien/Documents/smartnoise-samples/venv/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /Users/damien/Documents/smartnoise-samples/venv/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /Users/damien/Documents/smartnoise-samples/venv/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /Users/damien/Documents/smartnoise-samples/venv/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /Users/damien/Documents/smartnoise-samples/venv/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /Users/damien/Documents/smartnoise-samples/venv/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /Users/damien/Documents/smartnoise-samples/venv/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /Users/damien/Documents/smartnoise-samples/venv/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /Users/damien/Documents/smartnoise-samples/venv/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    accelerate_info:
      NOT AVAILABLE

    lapack_info:
    customize UnixCCompiler
      libraries lapack not found in ['/Users/damien/Documents/smartnoise-samples/venv/lib', '/usr/local/lib', '/usr/lib']
      NOT AVAILABLE

    /private/var/folders/zf/b889zp6j40n1c5q7j4x71r4w0000gn/T/pip-build-env-0ftgz7og/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      if getattr(self, '_calc_info_{}'.format(lapack))():
    lapack_src_info:
      NOT AVAILABLE

    /private/var/folders/zf/b889zp6j40n1c5q7j4x71r4w0000gn/T/pip-build-env-0ftgz7og/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      if getattr(self, '_calc_info_{}'.format(lapack))():
      NOT AVAILABLE

    Traceback (most recent call last):
      File "/Users/damien/Documents/smartnoise-samples/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/Users/damien/Documents/smartnoise-samples/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/damien/Documents/smartnoise-samples/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 151, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/zf/b889zp6j40n1c5q7j4x71r4w0000gn/T/pip-build-env-0ftgz7og/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/private/var/folders/zf/b889zp6j40n1c5q7j4x71r4w0000gn/T/pip-build-env-0ftgz7og/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 258, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/private/var/folders/zf/b889zp6j40n1c5q7j4x71r4w0000gn/T/pip-build-env-0ftgz7og/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 583, in <module>
        setup_package()
      File "setup.py", line 579, in setup_package
        setup(**metadata)
      File "/private/var/folders/zf/b889zp6j40n1c5q7j4x71r4w0000gn/T/pip-build-env-0ftgz7og/overlay/lib/python3.9/site-packages/numpy/distutils/core.py", line 137, in setup
        config = configuration()
      File "setup.py", line 477, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found. Note: Accelerate is no longer supported.
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/53/10/776750d57ade26522478a92a2e14035868624a6a62f4157b0cc5abd4a980/scipy-1.5.2.tar.gz#sha256=066c513d90eb3fd7567a9e150828d39111ebd88d3e924cdfc9f8ce19ab6f90c9 (from https://pypi.org/simple/scipy/) (requires-python:>=3.6). Command errored out with exit status 1: /Users/damien/Documents/smartnoise-samples/venv/bin/python3.9 /Users/damien/Documents/smartnoise-samples/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/zf/b889zp6j40n1c5q7j4x71r4w0000gn/T/tmpav4k1mne Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement scipy==1.5.2 (from versions: 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 1.0.0b1, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.1.0rc1, 1.1.0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0rc1, 1.5.0rc2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0rc1, 1.6.0rc2, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0rc1, 1.7.0rc2, 1.7.0, 1.7.1)
ERROR: No matching distribution found for scipy==1.5.2
```

All previous steps described in the [README.md](https://github.com/opendp/smartnoise-samples#installation) worked fine. I'm using macoS Big Sur version 11.5.1 on a 2020 13-inch MacBook Pro with an Intel Core i5 inside.

**Comment by raprasad** [comment]
Thanks, @TedTed, we'll get back to you soon.

**Comment by Shoeboxam** [comment]
I am also on MacOS, I've been using Python 3.6 and 3.8. Sure enough, the install fails on 3.9 (what you're using), but my issue was with numpy. At least in my case, I got things working by loosening the pins in the `requirements.txt`- even loosening pins that were seemingly unrelated to the package.

```
jupyter==1.0.0
jupyter-client==6.1.7
jupyter-console==6.2.0
jupyter-core==4.6.3
jupyterlab==2.2.9
jupyterlab-pygments==0.1.2
jupyterlab-server==1.2.0
matplotlib==3.3.1
numpy
# opendp-smartnoise==0.1.3.1
opendp-smartnoise==0.1.4
pandas
scipy<2.0.0
seaborn==0.11.0
z3-solver==4.8.9.0

# for notebook testing
#nbclient==0.5.3
```

I can't replicate the sklearn issue, but you may find un-pinning those dependencies will help you. I took a quick look through the SDK dependencies and I noticed scipy is only `<2.0.0`, so I've adjusted the requirements file above. Let me know if that resolves your issue and we can get a PR going with requirements relaxations.

Fair warning, steer clear of the `analysis` and `attacks` folders. I opened another issue (#107) to make this more clear. Those folders correspond to the predecessor of the OpenDP library. If you are looking into the SDK, you're in the right place.

**Comment by joshua-oss** [comment]
Hi Ted, thanks for reporting.  There was a dependency conflict where our synthesizers depended on an old version of ctgan which wasn't compatible with any versions of numpy supported on MacOS with Python 3.9.  We have split the functionality into 3 packages, `smartnoise-sql`, `smartnoise-synth` and `smartnoise-eval`.  We've also updated the synthesizers to work with the newest ctgan, so it should also work with python 3.9 now.  The new `smartnoise-sql` package uses the new `opendp` rust library instead of the older `smartnoise-core` rust library, and is tested in python 3.7-3.9.  It is know to not work in python 3.10, due to scipy dependency.  We are working to eliminate that dependency so we can support 3.10.

The samples repo is still out of sync with the new package split, we are working to update.  The samples on smartnoise-sdk and opendp repos should all be in sync with latest versions, though.

**Comment by raprasad** [comment]
@TedTed ^ Let us know if that helps. Updates are underway for the associated notebooks/docs. Thanks.

**Comment by TedTed** [comment]
@Shoeboxam's workaround works for me, thanks for the help =)
